export { default as CheckedIcon } from './checked.svg';
export { default as DarkThemeIcon } from './dark_theme.svg';
export { default as InfoCircle } from './info.svg';
export { default as LightThemeIcon } from './light_theme.svg';
export { default as Logo } from './logo.svg';
export { default as PromotionalIcon } from './no_ads.svg';
export { default as OptionsIcon } from './options.svg';
export { default as SocialIcon } from './share.svg';
export { default as WarningIcon } from './warning.svg';
